##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C ./nibbler
	make -C ./solarFox

clean:
	make clean -C ./nibbler
	make clean -C ./solarFox

fclean:	clean
	make fclean -C ./nibbler
	make fclean -C ./solarFox

re:	fclean all

.PHONY:	all clean fclean
